// import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/components/Navbar";
import ThemeContext from "@/components/ThemeContext";
import Head from "next/head";
import { Nunito_Sans } from 'next/font/google';
// import ThemeContext from "../components/ThemeContext"


// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

const nunitoSans = Nunito_Sans({
  subsets: ['latin'], // Specify the subsets
  weight: ['400', '700'], // Specify font weights
  display: 'swap', // Optional, controls the font-display behavior
});

export const metadata = {
  title: "Rest Countries",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
       <Head>
        <title>{metadata.title}</title>
      </Head>
      <body
        className={`${nunitoSans.className} antialiased`}
      >
        < ThemeContext>
          < Navbar />
          {children}
        </ThemeContext>
      </body>
    </html>
  );
}
